USE CHAKRA_ERP
GO

truncate table BRANDMASTER

SET IDENTITY_INSERT dbo.BRANDMASTER ON 
GO

INSERT INTO dbo.BRANDMASTER
     (BRNDID,BRNDDESC,BRNDCODE,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE)
Select BRNDID,BRNDDESC,BRNDCODE,'admin',1,DISPSTATUS,getdate()
From BRANDMASTER_29042024

--Update BRANDMASTER Set COMPYID = 1

SET IDENTITY_INSERT dbo.BRANDMASTER OFF
GO

GO


