
USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_01]
ON [dbo].[RECEIPTMASTER] ([COMPYID],[REGSTRID],[RCPTTYPE])
INCLUDE ([BRNCHID],[RCPTGAMT])
GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_02]
ON [dbo].[RECEIPTMASTER] ([COMPYID],[REGSTRID],[RCPTMODE],[RCPTTYPE],[RCPTDATE])
INCLUDE ([BRNCHID])
GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_03]
ON [dbo].[RECEIPTDETAIL] ([RCPTMID])
INCLUDE ([RCPTPAMT],[RCPTIAMT],[RCPTLFEE],[RCPTDCAMT],[RCPTADVAMT],[RCPTSTAMT],[RCPTFIAMT])
GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_04]
ON [dbo].[LOAN_LATEFEE_MASTER] ([COMPYID],[LFMDATE])
INCLUDE ([LOANMID],[LFMAMT])
GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_05]
ON [dbo].[LOANMASTER] ([BRNCHID])

GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_06]
ON [dbo].[LOAN_LATEFEE_MASTER] ([COMPYID],[LOANMID],[LFMDATE])
INCLUDE ([LFMAMT])
GO


------

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Tmp_Day_Book_Detail_XML_NC_01]
ON [dbo].[TMP_DAY_BOOK_RPT] ([KUSRID])
INCLUDE ([VCHRNO],[VCHRDATE],[COL2],[COL3],[COL4],[COL5],[COL6],[COL7],[COL8],[COL9],[COL10],[COL11],[COL12],[DISPORDER],[RPTID])
GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Tmp_Day_Book_Detail_XML_NC_02]
ON [dbo].[TMP_DAY_BOOK_RPT] ([KUSRID],[RPTID])

GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Tmp_Day_Book_Detail_XML_NC_03]
ON [dbo].[TMP_DAY_BOOK_RPT] ([VCHRDATE])

GO

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Tmp_Day_Book_Detail_XML_NC_04]
ON [dbo].[TMP_DAY_BOOK_RPT] ([VCHRNO])

GO

-----

USE [CHAKRA_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Cash_Book_Ledger_Detail_Assgn_NC_07]
ON [dbo].[RECEIPTMASTER] ([COMPYID],[REGSTRID],[RCPTMODE],[RCPTTYPE],[RCPTDATE])
INCLUDE ([BRNCHID],[DRCPTNO],[CATENAME])
GO

