USE CHAKRA_ERP
GO

truncate table LOCATIONMASTER

SET IDENTITY_INSERT dbo.LOCATIONMASTER ON 
GO

INSERT INTO dbo.LOCATIONMASTER
     (LOCTID,LOCTDESC,LOCTCODE,STATEID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE)
Select LOCTID,LOCTDESC,LOCTCODE,0,'admin',1,DISPSTATUS,getdate()
From LOCATIONMASTER_29042024

--Update LOCATIONMASTER Set COMPYID = 1

SET IDENTITY_INSERT dbo.LOCATIONMASTER OFF
GO

GO


