USE CHAKRA_ERP
GO

truncate table MODELMASTER

SET IDENTITY_INSERT dbo.MODELMASTER ON 
GO

INSERT INTO dbo.MODELMASTER
     (MDLID,MDLDESC,MDLCODE,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE)
Select MDLID,MDLDESC,MDLCODE,'admin',1,DISPSTATUS,getdate()
From MODELMASTER_29042024

--Update MODELMASTER Set COMPYID = 1

SET IDENTITY_INSERT dbo.MODELMASTER OFF
GO

GO


