USE [CHAKRA_ERP]
GO
--select  getdate()
truncate table RECEIPTMASTER

SET IDENTITY_INSERT [dbo].[RECEIPTMASTER] ON 
GO
INSERT INTO dbo.[RECEIPTMASTER]
           (RCPTMID,COMPYID,REGSTRID,BRNCHID,RCPTDATE,RCPTNO,DRCPTNO,CATEID,CATENAME,RCPTMODE,
		   RCPTCHQNO,RCPTCHQDATE,RCPTBANK,RCPTBRNCH,RCPTGAMT,RCPTNAMT,RCPTEAMT,RCPTLFEE,
		   RCPTAMTWRDS,DISPSTATUS,PRCSDATE,NARRATION,RCPTTYPE,CUSRID,LMUSRID)

Select rm.RCPTMID,rm.COMPYID,REGSTRID,rm.BRNCHID, RCPTDATE,RCPTNO,DRCPTNO,rm.CATEID,rm.CATENAME,RCPTMODE,
       RCPTCHQNO,isnull(RCPTCHQDATE, null),RCPTBANK,RCPTBRNCH,RCPTGAMT,RCPTNAMT,RCPTEAMT,rm.RCPTLFEE,
	   RCPTAMTWRDS,rm.DISPSTATUS,getdate(),NARRATION,RCPTTYPE,'admin','admin'
From RECEIPTMASTER_29042024 rm
--left outer Join RECEIPTDETAIL_07112023 rd On rm.RCPTMID = rd.RCPTMID
--left outer Join LOANMASTER lm On rd.LOANMID = lm.LOANMID
--left outer Join BRANCHMASTERS bm On lm.BRNCHID = bm.BRNCHID
--where RCPTTYPE = 0
--Group by rm.RCPTMID,rm.COMPYID,REGSTRID,rm.BRNCHID,RCPTDATE,RCPTNO,DRCPTNO,rm.CATEID,rm.CATENAME,RCPTMODE,
--       RCPTCHQNO,RCPTCHQDATE,RCPTBANK,RCPTBRNCH,RCPTGAMT,RCPTNAMT,RCPTEAMT,rm.RCPTLFEE,
--	   RCPTAMTWRDS,rm.DISPSTATUS,NARRATION,RCPTTYPE,lm.LOAN_CATE_CODE,
--	   lm.LOANSDATE,lm.LOANEDATE,LOANSDATE,bm.BRNCHNAME,lm.LOAN_CATE_CODE,rd.LOANMID

--Select * From RECEIPTMASTER
--Inner Join RECEIPTMASTER_29042024 On RECEIPTMASTER.RCPTMID = RECEIPTMASTER_29042024.RCPTMID

--select RCPTMID,  RCPTDATE
--from RECEIPTMASTER_29042024
--where RCPTDATE < '1900-01-01' or RCPTDATE > '2079-06-06'

--Update RECEIPTMASTER Set RCPTDATE = RECEIPTMASTER_29042024.RCPTDATE
--From RECEIPTMASTER
--Inner Join RECEIPTMASTER_29042024 On RECEIPTMASTER.RCPTMID = RECEIPTMASTER_29042024.RCPTMID

Update RECEIPTMASTER Set COMPYID = 1

SET IDENTITY_INSERT [dbo].[RECEIPTMASTER] OFF
GO

GO


