USE [CHAKRA_ERP]
GO
--select  getdate()
truncate table RECEIPTDETAIL

SET IDENTITY_INSERT [dbo].[RECEIPTDETAIL] ON 
GO
INSERT INTO dbo.RECEIPTDETAIL
           (RCPTDID,RCPTMID,LOANMID,VHLNO,LOANAMT,EMIAMT,RCPTNOI,RCPTPAMT,RCPTIAMT,RCPTLFEE,RCPTDDATE
           ,RCPTFDATE,RCPTIWAMT,RCPTLOPAMT,RCPTDCAMT,RCPTADVAMT,RCPTSTAMT,RCPTFIAMT)

Select RCPTDID,RCPTMID,LOANMID,VHLNO,LOANAMT,EMIAMT,RCPTNOI,RCPTPAMT,RCPTIAMT,RCPTLFEE,RCPTDDATE
           ,RCPTFDATE,RCPTIWAMT,RCPTLOPAMT,RCPTDCAMT,RCPTADVAMT,RCPTSTAMT,RCPTFIAMT
From RECEIPTDETAIL_29042024 

SET IDENTITY_INSERT [dbo].[RECEIPTDETAIL] OFF
GO

GO


