USE [SYNC]
GO

/****** Object:  View [dbo].[Z_SALES_EINVOICE_DETAILS_04]    Script Date: 15/08/2023 13:27:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_SALES_EINVOICE_DETAILS_04]
AS
SELECT        dbo.TRANSACTIONDETAIL.TRANDID, dbo.TRANSACTIONDETAIL.TRANMID, dbo.TRANSACTIONDETAIL.TRANDAMT, 
                         ROUND(dbo.TRANSACTIONDETAIL.TRANDQTY * dbo.Z_SALES_EINVOICE_DETAILS_02.CGSTAMT / dbo.Z_SALES_EINVOICE_DETAILS_03.DQTY, 2) AS CGSTAMT, 
                         ROUND(dbo.TRANSACTIONDETAIL.TRANDQTY * dbo.Z_SALES_EINVOICE_DETAILS_02.SGSTAMT / dbo.Z_SALES_EINVOICE_DETAILS_03.DQTY, 2) AS SGSTAMT, 
                         ROUND(dbo.TRANSACTIONDETAIL.TRANDQTY * dbo.Z_SALES_EINVOICE_DETAILS_02.IGSTAMT / dbo.Z_SALES_EINVOICE_DETAILS_03.DQTY, 2) AS IGSTAMT
FROM            dbo.TRANSACTIONDETAIL INNER JOIN
                         dbo.PRODUCTMASTER ON dbo.TRANSACTIONDETAIL.TRANDREFID = dbo.PRODUCTMASTER.PRDTID INNER JOIN
                         dbo.HSNCODEMASTER ON dbo.PRODUCTMASTER.HSNID = dbo.HSNCODEMASTER.HSNID INNER JOIN
                         dbo.Z_SALES_EINVOICE_DETAILS_02 ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.Z_SALES_EINVOICE_DETAILS_02.TRANMID INNER JOIN
                         dbo.Z_SALES_EINVOICE_DETAILS_03 ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.Z_SALES_EINVOICE_DETAILS_03.TRANMID
GO


