USE [SYNC]
GO

/****** Object:  View [dbo].[Z_SALES_EINVOICE_DETAILS_03]    Script Date: 15/08/2023 13:27:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_SALES_EINVOICE_DETAILS_03]
AS
SELECT        TRANMID, SUM(TRANDQTY) AS DQTY
FROM            dbo.TRANSACTIONDETAIL
GROUP BY TRANMID
GO


