//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubMembership.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Discriminator { get; set; }
        public string NPassword { get; set; }
        public int BrnchId { get; set; }
        public string UBrnchName { get; set; }
        public int DBrnchId { get; set; }
        public string DeptName { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
    }
}
