//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHAKRA_ERP.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CHAKRA_ERPEntities : DbContext
    {
        public CHAKRA_ERPEntities()
            : base("name=CHAKRA_ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<VW_USER_DETAILS> VW_USER_DETAILS { get; set; }
    
        public virtual ObjectResult<PR_ACCOUNTINGYEAR_ID_CHK_Result> PR_ACCOUNTINGYEAR_ID_CHK(Nullable<int> pFYear, Nullable<int> pTYear)
        {
            var pFYearParameter = pFYear.HasValue ?
                new ObjectParameter("PFYear", pFYear) :
                new ObjectParameter("PFYear", typeof(int));
    
            var pTYearParameter = pTYear.HasValue ?
                new ObjectParameter("PTYear", pTYear) :
                new ObjectParameter("PTYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ACCOUNTINGYEAR_ID_CHK_Result>("PR_ACCOUNTINGYEAR_ID_CHK", pFYearParameter, pTYearParameter);
        }
    
        public virtual ObjectResult<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result> PR_COMPANYACCOUNTINGDETAIL_ID_CHK(Nullable<int> pCompId, Nullable<int> pYrId)
        {
            var pCompIdParameter = pCompId.HasValue ?
                new ObjectParameter("PCompId", pCompId) :
                new ObjectParameter("PCompId", typeof(int));
    
            var pYrIdParameter = pYrId.HasValue ?
                new ObjectParameter("PYrId", pYrId) :
                new ObjectParameter("PYrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result>("PR_COMPANYACCOUNTINGDETAIL_ID_CHK", pCompIdParameter, pYrIdParameter);
        }
    
        public virtual ObjectResult<pr_SearchAccountGroup_Result> pr_SearchAccountGroup(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchAccountGroup_Result>("pr_SearchAccountGroup", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchAccountHeadMaster_Result> pr_SearchAccountHeadMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchAccountHeadMaster_Result>("pr_SearchAccountHeadMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchCompanyMaster_Result> pr_SearchCompanyMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchCompanyMaster_Result>("pr_SearchCompanyMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchDepartmentMaster_Result> pr_SearchDepartmentMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchDepartmentMaster_Result>("pr_SearchDepartmentMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchDesignationMaster_Result> pr_SearchDesignationMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchDesignationMaster_Result>("pr_SearchDesignationMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Roles_Result> pr_Search_Roles(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Roles_Result>("pr_Search_Roles", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchRegionMaster_Result> pr_SearchRegionMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchRegionMaster_Result>("pr_SearchRegionMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchStateMaster_Result> pr_SearchStateMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchStateMaster_Result>("pr_SearchStateMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual int pr_USER_MENU_DETAIL_ASSGN(string pKUSRID)
        {
            var pKUSRIDParameter = pKUSRID != null ?
                new ObjectParameter("PKUSRID", pKUSRID) :
                new ObjectParameter("PKUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_USER_MENU_DETAIL_ASSGN", pKUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchBrandMaster_Result> pr_SearchBrandMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchBrandMaster_Result>("pr_SearchBrandMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchModelMaster_Result> pr_SearchModelMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchModelMaster_Result>("pr_SearchModelMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchColourMaster_Result> pr_SearchColourMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchColourMaster_Result>("pr_SearchColourMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchCategoryTypeMaster01_Result> pr_SearchCategoryTypeMaster01(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchCategoryTypeMaster01_Result>("pr_SearchCategoryTypeMaster01", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchSchemeMaster_Result> pr_SearchSchemeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSchemeMaster_Result>("pr_SearchSchemeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchLoanTypeMaster_Result> pr_SearchLoanTypeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLoanTypeMaster_Result>("pr_SearchLoanTypeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual int pr_SearchTestMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_SearchTestMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Employoee_Master_Link_Ctrl_Assgn_Result> pr_Employoee_Master_Link_Ctrl_Assgn(Nullable<int> pCateId)
        {
            var pCateIdParameter = pCateId.HasValue ?
                new ObjectParameter("PCateId", pCateId) :
                new ObjectParameter("PCateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Employoee_Master_Link_Ctrl_Assgn_Result>("pr_Employoee_Master_Link_Ctrl_Assgn", pCateIdParameter);
        }
    
        public virtual ObjectResult<pr_SearchEmployeeMaster_Result> pr_SearchEmployeeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchEmployeeMaster_Result>("pr_SearchEmployeeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchCategory_Master_Result> pr_SearchCategory_Master(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchCategory_Master_Result>("pr_SearchCategory_Master", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchDealerMaster_Result> pr_SearchDealerMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCateType)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCateTypeParameter = pCateType.HasValue ?
                new ObjectParameter("PCateType", pCateType) :
                new ObjectParameter("PCateType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchDealerMaster_Result>("pr_SearchDealerMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCateTypeParameter);
        }
    
        public virtual ObjectResult<pr_SearchLocationMaster_Result> pr_SearchLocationMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLocationMaster_Result>("pr_SearchLocationMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchBankMaster_Result> pr_SearchBankMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchBankMaster_Result>("pr_SearchBankMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<Pr_Loan_Status_Pending_Amount_Assgn_Result> Pr_Loan_Status_Pending_Amount_Assgn(Nullable<int> pCompYId, Nullable<int> pLoanMId, Nullable<int> pCateId)
        {
            var pCompYIdParameter = pCompYId.HasValue ?
                new ObjectParameter("PCompYId", pCompYId) :
                new ObjectParameter("PCompYId", typeof(int));
    
            var pLoanMIdParameter = pLoanMId.HasValue ?
                new ObjectParameter("PLoanMId", pLoanMId) :
                new ObjectParameter("PLoanMId", typeof(int));
    
            var pCateIdParameter = pCateId.HasValue ?
                new ObjectParameter("PCateId", pCateId) :
                new ObjectParameter("PCateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Loan_Status_Pending_Amount_Assgn_Result>("Pr_Loan_Status_Pending_Amount_Assgn", pCompYIdParameter, pLoanMIdParameter, pCateIdParameter);
        }
    
        public virtual ObjectResult<pr_Customer_Code_Search_Assgn_Result> pr_Customer_Code_Search_Assgn(Nullable<int> pBRNCHID, string filterTerm)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Customer_Code_Search_Assgn_Result>("pr_Customer_Code_Search_Assgn", pBRNCHIDParameter, filterTermParameter);
        }
    
        public virtual ObjectResult<pr_Receipt_Customer_Code_Search_Assgn_Result> pr_Receipt_Customer_Code_Search_Assgn(Nullable<int> pBRNCHID, string filterTerm)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Receipt_Customer_Code_Search_Assgn_Result>("pr_Receipt_Customer_Code_Search_Assgn", pBRNCHIDParameter, filterTermParameter);
        }
    
        public virtual ObjectResult<pr_Receipt_Detail_Ctrl_Assgn_Result> pr_Receipt_Detail_Ctrl_Assgn(Nullable<int> pRCPTMID)
        {
            var pRCPTMIDParameter = pRCPTMID.HasValue ?
                new ObjectParameter("PRCPTMID", pRCPTMID) :
                new ObjectParameter("PRCPTMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Receipt_Detail_Ctrl_Assgn_Result>("pr_Receipt_Detail_Ctrl_Assgn", pRCPTMIDParameter);
        }
    
        public virtual ObjectResult<pr_LoanLateFee_Customer_Code_Search_Assgn_Result> pr_LoanLateFee_Customer_Code_Search_Assgn(Nullable<int> pBRNCHID, string filterTerm)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_LoanLateFee_Customer_Code_Search_Assgn_Result>("pr_LoanLateFee_Customer_Code_Search_Assgn", pBRNCHIDParameter, filterTermParameter);
        }
    
        public virtual ObjectResult<pr_Late_Fee_Master_Ctrl_Assgn_Result> pr_Late_Fee_Master_Ctrl_Assgn(Nullable<int> pLFMID)
        {
            var pLFMIDParameter = pLFMID.HasValue ?
                new ObjectParameter("PLFMID", pLFMID) :
                new ObjectParameter("PLFMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Late_Fee_Master_Ctrl_Assgn_Result>("pr_Late_Fee_Master_Ctrl_Assgn", pLFMIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchLoanNocStatusMaster_Result> pr_SearchLoanNocStatusMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLoanNocStatusMaster_Result>("pr_SearchLoanNocStatusMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<pr_Loan_Status_Detail_Ctrl_Assgn_Result> pr_Loan_Status_Detail_Ctrl_Assgn(Nullable<int> pLOANMID)
        {
            var pLOANMIDParameter = pLOANMID.HasValue ?
                new ObjectParameter("PLOANMID", pLOANMID) :
                new ObjectParameter("PLOANMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Loan_Status_Detail_Ctrl_Assgn_Result>("pr_Loan_Status_Detail_Ctrl_Assgn", pLOANMIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchLoanLateeFee_Result> pr_SearchLoanLateeFee(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLoanLateeFee_Result>("pr_SearchLoanLateeFee", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<pr_SearchBranchMaster_Result> pr_SearchBranchMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchBranchMaster_Result>("pr_SearchBranchMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchCustomerMaster_Result> pr_SearchCustomerMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pBRNCHID, Nullable<int> type)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchCustomerMaster_Result>("pr_SearchCustomerMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pBRNCHIDParameter, typeParameter);
        }
    
        public virtual ObjectResult<pr_SearchExpenseDetail_Result> pr_SearchExpenseDetail(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchExpenseDetail_Result>("pr_SearchExpenseDetail", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<pr_Account_Head_Search_Assgn_Result> pr_Account_Head_Search_Assgn(string filterTerm)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Account_Head_Search_Assgn_Result>("pr_Account_Head_Search_Assgn", filterTermParameter);
        }
    
        public virtual ObjectResult<pr_Search_LOC_Status_Grid_Assgn_Result> pr_Search_LOC_Status_Grid_Assgn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, string pKUSRID, Nullable<int> pBRNCHID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pKUSRIDParameter = pKUSRID != null ?
                new ObjectParameter("PKUSRID", pKUSRID) :
                new ObjectParameter("PKUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_LOC_Status_Grid_Assgn_Result>("pr_Search_LOC_Status_Grid_Assgn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDATEParameter, pEDATEParameter, pKUSRIDParameter, pBRNCHIDParameter);
        }
    
        public virtual ObjectResult<pr_Receipt_Amount_Received_SMS_Detail_Assgn_Result> pr_Receipt_Amount_Received_SMS_Detail_Assgn(Nullable<int> pRcptMId)
        {
            var pRcptMIdParameter = pRcptMId.HasValue ?
                new ObjectParameter("PRcptMId", pRcptMId) :
                new ObjectParameter("PRcptMId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Receipt_Amount_Received_SMS_Detail_Assgn_Result>("pr_Receipt_Amount_Received_SMS_Detail_Assgn", pRcptMIdParameter);
        }
    
        public virtual ObjectResult<pr_Loan_Sanctioned_SMS_Detail_Assgn_Result> pr_Loan_Sanctioned_SMS_Detail_Assgn(Nullable<int> pLoanMId)
        {
            var pLoanMIdParameter = pLoanMId.HasValue ?
                new ObjectParameter("PLoanMId", pLoanMId) :
                new ObjectParameter("PLoanMId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Loan_Sanctioned_SMS_Detail_Assgn_Result>("pr_Loan_Sanctioned_SMS_Detail_Assgn", pLoanMIdParameter);
        }
    
        public virtual ObjectResult<pr_Search_CollectionReceipt_Result> pr_Search_CollectionReceipt(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, string pCUSRID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_CollectionReceipt_Result>("pr_Search_CollectionReceipt", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter, pCUSRIDParameter);
        }
    
        public virtual ObjectResult<PR_GET_USERNAME_Result> PR_GET_USERNAME(Nullable<int> pBRNCHID)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_USERNAME_Result>("PR_GET_USERNAME", pBRNCHIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchLoanMaster_Result> pr_SearchLoanMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLoanMaster_Result>("pr_SearchLoanMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<pr_SearchReceiptMaster_Result> pr_SearchReceiptMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchReceiptMaster_Result>("pr_SearchReceiptMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<pr_CUSTOMER_PENDING_LOAN_LIST_INSRT_001_Result> pr_CUSTOMER_PENDING_LOAN_LIST_INSRT_001(string pKUSRID, Nullable<int> pCATEID, Nullable<System.DateTime> pSDATE)
        {
            var pKUSRIDParameter = pKUSRID != null ?
                new ObjectParameter("PKUSRID", pKUSRID) :
                new ObjectParameter("PKUSRID", typeof(string));
    
            var pCATEIDParameter = pCATEID.HasValue ?
                new ObjectParameter("PCATEID", pCATEID) :
                new ObjectParameter("PCATEID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_CUSTOMER_PENDING_LOAN_LIST_INSRT_001_Result>("pr_CUSTOMER_PENDING_LOAN_LIST_INSRT_001", pKUSRIDParameter, pCATEIDParameter, pSDATEParameter);
        }
    
        public virtual ObjectResult<PR_BRANCH_DETAILS_DASHBOARD_CHART_Result> PR_BRANCH_DETAILS_DASHBOARD_CHART(Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pEMPID)
        {
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pEMPIDParameter = pEMPID.HasValue ?
                new ObjectParameter("PEMPID", pEMPID) :
                new ObjectParameter("PEMPID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_BRANCH_DETAILS_DASHBOARD_CHART_Result>("PR_BRANCH_DETAILS_DASHBOARD_CHART", pSDATEParameter, pEDATEParameter, pEMPIDParameter);
        }
    
        public virtual ObjectResult<PR_AREA_WISE_DETAILS_DASHBOARD_CHART_Result> PR_AREA_WISE_DETAILS_DASHBOARD_CHART(Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pEMPID)
        {
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pEMPIDParameter = pEMPID.HasValue ?
                new ObjectParameter("PEMPID", pEMPID) :
                new ObjectParameter("PEMPID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_AREA_WISE_DETAILS_DASHBOARD_CHART_Result>("PR_AREA_WISE_DETAILS_DASHBOARD_CHART", pSDATEParameter, pEDATEParameter, pEMPIDParameter);
        }
    
        public virtual ObjectResult<pr_Loanstatus_Customer_Code_Search_Assgn_Result> pr_Loanstatus_Customer_Code_Search_Assgn(string filterTerm)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Loanstatus_Customer_Code_Search_Assgn_Result>("pr_Loanstatus_Customer_Code_Search_Assgn", filterTermParameter);
        }
    
        public virtual ObjectResult<pr_FRM_VHLNO_AMOUNT_NOI_Result> pr_FRM_VHLNO_AMOUNT_NOI(Nullable<int> pCOMPYID, Nullable<int> pLOANMID)
        {
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pLOANMIDParameter = pLOANMID.HasValue ?
                new ObjectParameter("PLOANMID", pLOANMID) :
                new ObjectParameter("PLOANMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_FRM_VHLNO_AMOUNT_NOI_Result>("pr_FRM_VHLNO_AMOUNT_NOI", pCOMPYIDParameter, pLOANMIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchLoanStatusMaster_Result> pr_SearchLoanStatusMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLoanStatusMaster_Result>("pr_SearchLoanStatusMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DASHBOARD_Result> PR_GET_RECEIPT_DASHBOARD(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DASHBOARD_Result>("PR_GET_RECEIPT_DASHBOARD", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DETAILS_DASHBOARD_Result> PR_GET_RECEIPT_DETAILS_DASHBOARD(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DETAILS_DASHBOARD_Result>("PR_GET_RECEIPT_DETAILS_DASHBOARD", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DETAILS_DASHBOARD_CONSOLIDATE_Result> PR_GET_RECEIPT_DETAILS_DASHBOARD_CONSOLIDATE(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DETAILS_DASHBOARD_CONSOLIDATE_Result>("PR_GET_RECEIPT_DETAILS_DASHBOARD_CONSOLIDATE", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE_Result> PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE_Result>("PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE_CONSOLIDATE_Result> PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE_CONSOLIDATE(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE_CONSOLIDATE_Result>("PR_GET_RECEIPT_DETAILS_DASHBOARD_EMP_WISE_CONSOLIDATE", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE_Result> PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE_Result>("PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE_CONSOLIDATE_Result> PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE_CONSOLIDATE(Nullable<int> pBRNCHID, string pCUSRID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE_CONSOLIDATE_Result>("PR_GET_RECEIPT_DETAILS_DASHBOARD_LOCATION_WISE_CONSOLIDATE", pBRNCHIDParameter, pCUSRIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<pr_Search_Collection_Agent_Pending_List_Result> pr_Search_Collection_Agent_Pending_List(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string pKUSRID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pKUSRIDParameter = pKUSRID != null ?
                new ObjectParameter("PKUSRID", pKUSRID) :
                new ObjectParameter("PKUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pDATEParameter = pDATE.HasValue ?
                new ObjectParameter("PDATE", pDATE) :
                new ObjectParameter("PDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Collection_Agent_Pending_List_Result>("pr_Search_Collection_Agent_Pending_List", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pKUSRIDParameter, pBRNCHIDParameter, pDATEParameter);
        }
    
        public virtual ObjectResult<pr_SearchLoanLateeFeeMaster_Result> pr_SearchLoanLateeFeeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCOMPYID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchLoanLateeFeeMaster_Result>("pr_SearchLoanLateeFeeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCOMPYIDParameter, pBRNCHIDParameter, pSDATEParameter, pEDATEParameter);
        }
    
        public virtual ObjectResult<Pr_On_Date_Remainder_SMS_View_Result> Pr_On_Date_Remainder_SMS_View(Nullable<int> pLOANMID, string pTEMPID)
        {
            var pLOANMIDParameter = pLOANMID.HasValue ?
                new ObjectParameter("PLOANMID", pLOANMID) :
                new ObjectParameter("PLOANMID", typeof(int));
    
            var pTEMPIDParameter = pTEMPID != null ?
                new ObjectParameter("PTEMPID", pTEMPID) :
                new ObjectParameter("PTEMPID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_On_Date_Remainder_SMS_View_Result>("Pr_On_Date_Remainder_SMS_View", pLOANMIDParameter, pTEMPIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchSMSOnDateRemainder_Result> pr_SearchSMSOnDateRemainder(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string pCUSRID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pDATEParameter = pDATE.HasValue ?
                new ObjectParameter("PDATE", pDATE) :
                new ObjectParameter("PDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSMSOnDateRemainder_Result>("pr_SearchSMSOnDateRemainder", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCUSRIDParameter, pBRNCHIDParameter, pDATEParameter);
        }
    
        public virtual ObjectResult<pr_SearchSMSOverDueRemainder_Result> pr_SearchSMSOverDueRemainder(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string pCUSRID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pDATE, Nullable<int> pLOCTID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pDATEParameter = pDATE.HasValue ?
                new ObjectParameter("PDATE", pDATE) :
                new ObjectParameter("PDATE", typeof(System.DateTime));
    
            var pLOCTIDParameter = pLOCTID.HasValue ?
                new ObjectParameter("PLOCTID", pLOCTID) :
                new ObjectParameter("PLOCTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSMSOverDueRemainder_Result>("pr_SearchSMSOverDueRemainder", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCUSRIDParameter, pBRNCHIDParameter, pDATEParameter, pLOCTIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchSMSPaymentRemainder_Result> pr_SearchSMSPaymentRemainder(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string pCUSRID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pDATEParameter = pDATE.HasValue ?
                new ObjectParameter("PDATE", pDATE) :
                new ObjectParameter("PDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSMSPaymentRemainder_Result>("pr_SearchSMSPaymentRemainder", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCUSRIDParameter, pBRNCHIDParameter, pDATEParameter);
        }
    
        public virtual ObjectResult<pr_SearchSMS_ECSRemainder_Result> pr_SearchSMS_ECSRemainder(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string pCUSRID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pDATEParameter = pDATE.HasValue ?
                new ObjectParameter("PDATE", pDATE) :
                new ObjectParameter("PDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSMS_ECSRemainder_Result>("pr_SearchSMS_ECSRemainder", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCUSRIDParameter, pBRNCHIDParameter, pDATEParameter);
        }
    
        public virtual ObjectResult<pr_SearchSMS_ECS_Bounced_Result> pr_SearchSMS_ECS_Bounced(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, string pCUSRID, Nullable<int> pBRNCHID, Nullable<System.DateTime> pDATE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCUSRIDParameter = pCUSRID != null ?
                new ObjectParameter("PCUSRID", pCUSRID) :
                new ObjectParameter("PCUSRID", typeof(string));
    
            var pBRNCHIDParameter = pBRNCHID.HasValue ?
                new ObjectParameter("PBRNCHID", pBRNCHID) :
                new ObjectParameter("PBRNCHID", typeof(int));
    
            var pDATEParameter = pDATE.HasValue ?
                new ObjectParameter("PDATE", pDATE) :
                new ObjectParameter("PDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchSMS_ECS_Bounced_Result>("pr_SearchSMS_ECS_Bounced", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCUSRIDParameter, pBRNCHIDParameter, pDATEParameter);
        }
    }
}
