//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubMembership.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClubMembershipDBEntities : DbContext
    {
        public ClubMembershipDBEntities()
            : base("name=ClubMembershipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<VW_USER_DETAILS> VW_USER_DETAILS { get; set; }
    
        public virtual ObjectResult<PR_ACCOUNTINGYEAR_ID_CHK_Result> PR_ACCOUNTINGYEAR_ID_CHK(Nullable<int> pFYear, Nullable<int> pTYear)
        {
            var pFYearParameter = pFYear.HasValue ?
                new ObjectParameter("PFYear", pFYear) :
                new ObjectParameter("PFYear", typeof(int));
    
            var pTYearParameter = pTYear.HasValue ?
                new ObjectParameter("PTYear", pTYear) :
                new ObjectParameter("PTYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ACCOUNTINGYEAR_ID_CHK_Result>("PR_ACCOUNTINGYEAR_ID_CHK", pFYearParameter, pTYearParameter);
        }
    
        public virtual ObjectResult<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result> PR_COMPANYACCOUNTINGDETAIL_ID_CHK(Nullable<int> pCompId, Nullable<int> pYrId)
        {
            var pCompIdParameter = pCompId.HasValue ?
                new ObjectParameter("PCompId", pCompId) :
                new ObjectParameter("PCompId", typeof(int));
    
            var pYrIdParameter = pYrId.HasValue ?
                new ObjectParameter("PYrId", pYrId) :
                new ObjectParameter("PYrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_COMPANYACCOUNTINGDETAIL_ID_CHK_Result>("PR_COMPANYACCOUNTINGDETAIL_ID_CHK", pCompIdParameter, pYrIdParameter);
        }
    
        public virtual ObjectResult<pr_SearchAccountGroup_Result> pr_SearchAccountGroup(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchAccountGroup_Result>("pr_SearchAccountGroup", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchAccountHeadMaster_Result> pr_SearchAccountHeadMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchAccountHeadMaster_Result>("pr_SearchAccountHeadMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchCompanyMaster_Result> pr_SearchCompanyMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchCompanyMaster_Result>("pr_SearchCompanyMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual int pr_SearchEmployeeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_SearchEmployeeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_USER_MENU_DETAIL_ASSGN_Result> pr_USER_MENU_DETAIL_ASSGN(string pKUSRID)
        {
            var pKUSRIDParameter = pKUSRID != null ?
                new ObjectParameter("PKUSRID", pKUSRID) :
                new ObjectParameter("PKUSRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_USER_MENU_DETAIL_ASSGN_Result>("pr_USER_MENU_DETAIL_ASSGN", pKUSRIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Roles_Result> pr_Search_Roles(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Roles_Result>("pr_Search_Roles", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchStateMaster_Result> pr_SearchStateMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchStateMaster_Result>("pr_SearchStateMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_SearchBloodGroupMaster_Result> pr_SearchBloodGroupMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchBloodGroupMaster_Result>("pr_SearchBloodGroupMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    }
}
