//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubMembership.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USER_DETAILS
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string UserName { get; set; }
    }
}
