USE CHAKRA_ERP
GO

TRUNCATE TABLE CUSTOMERMASTER

SET IDENTITY_INSERT [dbo].[CUSTOMERMASTER] ON 
GO

INSERT INTO dbo.CUSTOMERMASTER
           (CATEID, COMPYID,BRNCHID,CATENAME,CATEDNAME,LOCTID,ACHEADGID,CATEOADDR,CATEADDR,CATECODE
           ,CATEPHNID,CATEPHN1,CATEPHN2,CATEPHN3 ,CATEPHN4,CATEDSGN,DISPSTATUS,PRCSDATE
           ,CATESEX,CATEDOB,CATEPCODE,CATEPROOFNAME,CATEPROOFNO,CUSRID,LMUSRID,CATENO,STATEID)
Select CATEID, 1,BRNCHID,CATENAME,CATENAME,LOCTID,2,CATEOADDR,CATEADDR,CATECODE
           ,CATEPHNID,CATEPHN1,CATEPHN2,CATEPHN3 ,CATEPHN4,CATEDSGN,DISPSTATUS,PRCSDATE
           ,CATESEX,CATEDOB,CATEPCODE,CATEPROOFNAME,CATEPROOFNO,'admin','admin',CATEID,1
From CUSTOMERMASTER_29042024

SET IDENTITY_INSERT [dbo].[CUSTOMERMASTER] OFF
GO

GO


