USE CHAKRA_ERP
GO

truncate table DEALERMASTER

SET IDENTITY_INSERT dbo.DEALERMASTER ON 
GO

INSERT INTO dbo.DEALERMASTER
     (CATEID, COMPYID, BRNCHID, CATENAME, CATEDNAME, CATETYPE, CATEADDR, CATEPHNID, 
	 CATEPHN1, CATEPHN2, CATEPHN3, CATEPHN4, LOCTID, DEALERID, CATECODE, CUSTID, CUSRID, 
	 LMUSRID, DISPSTATUS, PRCSDATE)
Select CATEID, COMPYID, BRNCHID, CATENAME, CATEDNAME, CATETYPE, CATEADDR, CATEPHNID, 
	 CATEPHN1, CATEPHN2, CATEPHN3, CATEPHN4, LOCTNID, DEALERID, CATECODE, 0, 'admin', 
	 1, DISPSTATUS, PRCSDATE
From DEALERMASTER_29042024

Update DEALERMASTER Set COMPYID = 1

SET IDENTITY_INSERT dbo.DEALERMASTER OFF
GO

GO


