USE CHAKRA_ERP
GO

truncate table LOAN_NOC_STATUS_MASTER

SET IDENTITY_INSERT dbo.LOAN_NOC_STATUS_MASTER ON 
GO

INSERT INTO dbo.LOAN_NOC_STATUS_MASTER
           (LNMID, COMPYID,LNMDATE,LNMNO,LNMDNO,LOANMID,LNMRMKS,DISPSTATUS, PRCSDATE,CUSRID,LMUSRID)
Select LNMID, COMPYID,LNMDATE,LNMNO,LNMDNO,LOANMID,LNMRMKS,DISPSTATUS, PRCSDATE,'admin',1
From LOAN_NOC_STATUS_MASTER_29042024


Update LOAN_NOC_STATUS_MASTER Set COMPYID = 1

SET IDENTITY_INSERT [dbo].[LOAN_NOC_STATUS_MASTER] OFF
GO

GO


