USE CHAKRA_ERP
GO

truncate table LOAN_LATEFEE_MASTER

SET IDENTITY_INSERT dbo.LOAN_LATEFEE_MASTER ON 
GO

INSERT INTO dbo.LOAN_LATEFEE_MASTER
     (LFMID, COMPYID,LFMDATE,LFMNO,LFMDNO,LOANMID,LFMAMT,LFMRMKS,DISPSTATUS,PRCSDATE,CUSRID,LMUSRID)
Select LFMID, COMPYID,LFMDATE,LFMNO,LFMDNO,LOANMID,LFMAMT,LFMRMKS,DISPSTATUS,PRCSDATE,'admin',1
From LOAN_LATEFEE_MASTER_29042024

Update LOAN_LATEFEE_MASTER Set COMPYID = 1

SET IDENTITY_INSERT dbo.LOAN_LATEFEE_MASTER OFF
GO

GO


