  
  
  
  
ALTER PROCEDURE [dbo].[SP_CUSTOMERMASTER_UPDT]  
  
@PCATEID  INT,  
@PCATEGID  INT,  
@PCATENAME  VARCHAR(100),  
@PCATEDNAME VARCHAR(100),  
@PCATEADDR  VARCHAR(250),  
@PCATEPHNID VARCHAR(4),  
@PCATEPHN1  VARCHAR(25),  
@PCATEPHN2  VARCHAR(25),  
@PCATEPHN3  VARCHAR(25),  
@PCATEPHN4  VARCHAR(25),  
@PCATEPNAME VARCHAR(100),  
@PLOCTNID  INT,  
@PSTATEID INT,
@PCATEMAIL  VARCHAR(100),  
@PCATE_CST_NO VARCHAR(25),  
@PCATE_CST_DATE VARCHAR(25),  
@PCATE_ACODE VARCHAR(25),  
@PCATE_T_NO VARCHAR(25),  
@PCATE_LST_NO VARCHAR(25),  
@PCATE_LST_CODE VARCHAR(25),  
@PCATE_EX_NO VARCHAR(25),  
@PCATE_EX_ACNO VARCHAR(25),  
@PCATE_EX_ADDR VARCHAR(100),  
@PCATE_EX_RNG VARCHAR(50),  
@PCATE_EX_DVSN VARCHAR(50),  
@PCATE_EX_CRTE VARCHAR(50),  
@PCATE_EX_TRF VARCHAR(50),  
@PCATENO  INT,  
@PCATECODE  VARCHAR(25),  
@PCATEVCODE VARCHAR(25),  
@PDISPSTATUS SMALLINT,  
@PPRCSDATE  SMALLDATETIME,  
@PLDGRGID  INT,  
@PCUSRID  INT,  
@PLMUSRID  INT  
  
AS  
  
UPDATE CUSTOMERMASTER SET  
  
CATEGID =  @PCATEGID,  
CATENAME = @PCATENAME,  
CATEDNAME = @PCATEDNAME,  
CATEADDR = @PCATEADDR,  
CATEPHNID = @PCATEPHNID,  
CATEPHN1 = @PCATEPHN1,  
CATEPHN2 =  @PCATEPHN2,  
CATEPHN3 = @PCATEPHN3,  
CATEPHN4 =  @PCATEPHN4,  
CATEPNAME =  @PCATEPNAME,  
LOCTNID = @PLOCTNID,  
STATEID = @PSTATEID,
CATEMAIL = @PCATEMAIL,  
CATE_CST_NO = @PCATE_CST_NO,  
CATE_CST_DATE = @PCATE_CST_DATE,  
CATE_ACODE = @PCATE_ACODE,  
CATE_T_NO = @PCATE_T_NO,  
CATE_LST_NO =  @PCATE_LST_NO,  
CATE_LST_CODE =  @PCATE_LST_CODE,  
CATE_EX_NO = @PCATE_EX_NO,  
CATE_EX_ACNO =  @PCATE_EX_ACNO,  
CATE_EX_ADDR =  @PCATE_EX_ADDR,  
CATE_EX_RNG =  @PCATE_EX_RNG,  
CATE_EX_DVSN = @PCATE_EX_DVSN,  
CATE_EX_CRTE = @PCATE_EX_CRTE,  
CATE_EX_TRF = @PCATE_EX_TRF,  
CATENO = @PCATENO,  
CATECODE = @PCATECODE,  
CATEVCODE = @PCATEVCODE,  
DISPSTATUS =  @PDISPSTATUS,  
PRCSDATE = @PPRCSDATE,  
LDGRGID = @PLDGRGID,  
CUSRID = @PCUSRID,  
LMUSRID = @PLMUSRID  
  
WHERE  CATEID =  @PCATEID  
  
  