USE [SYNC]
GO
/****** Object:  Table [dbo].[STATEMASTER]    Script Date: 15/08/2023 13:34:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATEMASTER](
	[STATEID] [int] NOT NULL,
	[STATEDESC] [varchar](100) NOT NULL,
	[STATECODE] [varchar](15) NOT NULL,
	[CUSRID] [int] NOT NULL,
	[LMUSRID] [int] NOT NULL,
	[DISPSTATUS] [smallint] NOT NULL,
	[PRCSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_STATEMASTER] PRIMARY KEY CLUSTERED 
(
	[STATEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (1, N'Of all Locations…..!', N'ALL', 1, 1, 0, CAST(N'2023-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (2, N'TAMIL NADU', N'33', 1, 1, 0, CAST(N'2023-08-14T16:43:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (3, N'PONDY', N'34', 1, 1, 0, CAST(N'2023-08-14T16:43:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (4, N'KERALA', N'32', 1, 1, 0, CAST(N'2023-08-14T16:43:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (5, N'MAHARASHTRA', N'27', 1, 1, 0, CAST(N'2023-08-14T16:43:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (6, N'KARNATAKA', N'29', 1, 1, 0, CAST(N'2023-08-14T16:43:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (7, N'ASSAM', N'18', 1, 1, 0, CAST(N'2023-08-14T16:44:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (8, N'ANDHRA PRADESH', N'37', 1, 1, 0, CAST(N'2023-08-14T16:44:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (9, N'TELANGANA', N'36', 1, 1, 0, CAST(N'2023-08-14T16:44:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (10, N'WEST BENGAL', N'19', 1, 1, 0, CAST(N'2023-08-14T16:44:00.000' AS DateTime))
GO
INSERT [dbo].[STATEMASTER] ([STATEID], [STATEDESC], [STATECODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (11, N'GOA', N'30', 1, 1, 0, CAST(N'2023-08-14T16:44:00.000' AS DateTime))
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_Table_1_LOCTID]  DEFAULT ((0)) FOR [STATEID]
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_Table_1_LOCTDESC]  DEFAULT (NULL) FOR [STATEDESC]
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_Table_1_LOCTCODE]  DEFAULT (NULL) FOR [STATECODE]
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_STATEMASTER_CUSRID]  DEFAULT ((0)) FOR [CUSRID]
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_STATEMASTER_LMUSRID]  DEFAULT ((0)) FOR [LMUSRID]
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_STATEMASTER_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO
ALTER TABLE [dbo].[STATEMASTER] ADD  CONSTRAINT [DF_STATEMASTER_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO
