USE [SYNC]
GO

/****** Object:  View [dbo].[Z_SALES_EINVOICE_DETAILS]    Script Date: 15/08/2023 13:28:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_SALES_EINVOICE_DETAILS]
AS
SELECT        dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.REGSTRID, dbo.TRANSACTIONMASTER.TRANDATE, dbo.TRANSACTIONMASTER.TRANNO, RIGHT(dbo.TRANSACTIONMASTER.TRANDNO, 15) AS TRANDNO, 
                         dbo.COMPANYMASTER.COMPGSTNO, dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR1, dbo.COMPANYMASTER.COMPADDR2, dbo.COMPANYMASTER.COMPLOCTDESC, 
                         dbo.COMPANYMASTER.COMPPINCODE, dbo.COMPANYMASTER.COMPSTATECODE, dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, dbo.CUSTOMERMASTER.CATE_LST_NO AS CATE_GST_NO, 
                         dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.CUSTOMERMASTER.CATEADDR AS CATEADDR1, '' AS CATEADDR2, dbo.CUSTOMERMASTER.CATE_ACODE AS CATE_PINCODE, dbo.LOCATIONMASTER.LOCTDESC, 
                         dbo.STATEMASTER.STATEDESC, dbo.STATEMASTER.STATECODE, dbo.CUSTOMERMASTER.CATEPHN3 AS CATEPHN1, dbo.TRANSACTIONMASTER.TRANGAMT - ISNULL(dbo.Z_SALES_EINVOICE_DETAILS_01.DEDVALUE, 0) 
                         AS TRANGAMT, dbo.TRANSACTIONMASTER.TRANNAMT, dbo.Z_SALES_EINVOICE_DETAILS_02.CGSTAMT AS TRANCGSTAMT, dbo.Z_SALES_EINVOICE_DETAILS_02.SGSTAMT AS TRANSGSTAMT, 
                         dbo.Z_SALES_EINVOICE_DETAILS_02.IGSTAMT AS TRANIGSTAMT, dbo.Z_SALES_EINVOICE_DETAILS_02.ROAMT AS TRANROAMT, ISNULL(dbo.Z_SALES_EINVOICE_DETAILS_01.DEDVALUE, 0) AS DISCAMT
FROM            dbo.Z_SALES_EINVOICE_DETAILS_01 RIGHT OUTER JOIN
                         dbo.STATEMASTER RIGHT OUTER JOIN
                         dbo.Z_SALES_EINVOICE_DETAILS_02 INNER JOIN
                         dbo.TRANSACTIONMASTER INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.CUSTOMERMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CUSTOMERMASTER.CATEID ON dbo.Z_SALES_EINVOICE_DETAILS_02.TRANMID = dbo.TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.LOCATIONMASTER ON dbo.CUSTOMERMASTER.LOCTNID = dbo.LOCATIONMASTER.LOCTID ON dbo.STATEMASTER.STATEID = dbo.CUSTOMERMASTER.STATEID ON 
                         dbo.Z_SALES_EINVOICE_DETAILS_01.TRANMID = dbo.TRANSACTIONMASTER.TRANMID
GROUP BY dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.REGSTRID, dbo.TRANSACTIONMASTER.TRANDATE, dbo.TRANSACTIONMASTER.TRANNO, RIGHT(dbo.TRANSACTIONMASTER.TRANDNO, 15), 
                         dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANGAMT - ISNULL(dbo.Z_SALES_EINVOICE_DETAILS_01.DEDVALUE, 0), dbo.TRANSACTIONMASTER.TRANNAMT, 
                         dbo.Z_SALES_EINVOICE_DETAILS_02.CGSTAMT, dbo.Z_SALES_EINVOICE_DETAILS_02.SGSTAMT, dbo.Z_SALES_EINVOICE_DETAILS_02.IGSTAMT, dbo.Z_SALES_EINVOICE_DETAILS_02.ROAMT, 
                         dbo.STATEMASTER.STATECODE, dbo.CUSTOMERMASTER.CATE_LST_NO, dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPGSTNO, dbo.COMPANYMASTER.COMPADDR1, 
                         dbo.COMPANYMASTER.COMPADDR2, dbo.COMPANYMASTER.COMPLOCTDESC, dbo.COMPANYMASTER.COMPPINCODE, dbo.COMPANYMASTER.COMPSTATECODE, dbo.COMPANYMASTER.COMPPHN1, 
                         dbo.COMPANYMASTER.COMPMAIL, dbo.CUSTOMERMASTER.CATEADDR, dbo.LOCATIONMASTER.LOCTDESC, dbo.STATEMASTER.STATEDESC, dbo.CUSTOMERMASTER.CATEPHN3, 
                         ISNULL(dbo.Z_SALES_EINVOICE_DETAILS_01.DEDVALUE, 0), dbo.CUSTOMERMASTER.CATE_ACODE
GO


