USE [SYNC]
GO

/****** Object:  View [dbo].[Z_SALES_EINVOICE_DETAILS_02]    Script Date: 15/08/2023 13:27:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_SALES_EINVOICE_DETAILS_02]
AS
SELECT        TRANMID, SUM(CASE CFID WHEN 15 THEN DEDVALUE ELSE 0 END) AS CGSTAMT, SUM(CASE CFID WHEN 16 THEN DEDVALUE ELSE 0 END) AS SGSTAMT, SUM(CASE CFID WHEN 17 THEN DEDVALUE ELSE 0 END) 
                         AS IGSTAMT, SUM(CASE CFID WHEN 1 THEN DEDVALUE ELSE 0 END) AS ROAMT
FROM            dbo.TRANSACTIONMASTERFACTOR
GROUP BY TRANMID
GO


