USE [SYNC]
GO

/****** Object:  View [dbo].[Z_SALES_EINVOICE_DETAILS_01]    Script Date: 15/08/2023 13:28:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_SALES_EINVOICE_DETAILS_01]
AS
SELECT        TRANMID, SUM(DEDVALUE) AS DEDVALUE
FROM            dbo.TRANSACTIONMASTERFACTOR
WHERE        (DEDMODE = '-')
GROUP BY TRANMID
GO


