-- Create TRANSACTION_INVOICE_WEIGHT_DETAILS table if it doesn't exist
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TRANSACTION_INVOICE_WEIGHT_DETAILS' AND xtype='U')
BEGIN
    CREATE TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS](
        [TRANRID] [int] IDENTITY(1,1) NOT NULL,
        [TRANDID] [int] NOT NULL,
        [PACKMID] [int] NOT NULL,
        [PACKTMID] [int] NOT NULL,
        [SLABVALUE] [numeric](18, 3) NOT NULL,
        [PNDSVALUE] [numeric](18, 3) NOT NULL,
        [TOTALPNDS] [numeric](18, 3) NOT NULL,
        [PACKWGT] [numeric](18, 3) NOT NULL,
        [TOTALWGHT] [numeric](18, 3) NOT NULL,
        [ONEDOLLAR] [numeric](18, 3) NOT NULL,
        [TOTALDOLVAL] [numeric](18, 3) NOT NULL,
        [WEIGHTINKGS] [numeric](18, 3) NOT NULL,
        [PERKGRATE] [numeric](18, 3) NOT NULL,
        [CUSRID] [varchar](100) NOT NULL,
        [LMUSRID] [varchar](100) NOT NULL,
        [DISPSTATUS] [smallint] NOT NULL,
        [PRCSDATE] [datetime] NOT NULL,
     CONSTRAINT [PK_TRANSACTION_INVOICE_WEIGHT_DETAILS] PRIMARY KEY CLUSTERED 
    (
        [TRANRID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]

    PRINT 'TRANSACTION_INVOICE_WEIGHT_DETAILS table created successfully'
END
ELSE
BEGIN
    PRINT 'TRANSACTION_INVOICE_WEIGHT_DETAILS table already exists'
END

-- Add default constraints if they don't exist
IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKMID')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKMID] DEFAULT ((0)) FOR [PACKMID]
    PRINT 'Default constraint for PACKMID added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKTMID')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKTMID] DEFAULT ((0)) FOR [PACKTMID]
    PRINT 'Default constraint for PACKTMID added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_Table_1_VALUE')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_Table_1_VALUE] DEFAULT ((0)) FOR [SLABVALUE]
    PRINT 'Default constraint for SLABVALUE added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_Table_1_PNDVALUE')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_Table_1_PNDVALUE] DEFAULT ((0)) FOR [PNDSVALUE]
    PRINT 'Default constraint for PNDSVALUE added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_TOTALPNDS')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_TOTALPNDS] DEFAULT ((0)) FOR [TOTALPNDS]
    PRINT 'Default constraint for TOTALPNDS added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKWGT')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKWGT] DEFAULT ((0)) FOR [PACKWGT]
    PRINT 'Default constraint for PACKWGT added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_TOTALWGHT')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_TOTALWGHT] DEFAULT ((0)) FOR [TOTALWGHT]
    PRINT 'Default constraint for TOTALWGHT added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_ONEDOLLAR')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_ONEDOLLAR] DEFAULT ((0)) FOR [ONEDOLLAR]
    PRINT 'Default constraint for ONEDOLLAR added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_TOTALDOLVAL')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_TOTALDOLVAL] DEFAULT ((0)) FOR [TOTALDOLVAL]
    PRINT 'Default constraint for TOTALDOLVAL added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_WEIGHTINKGS')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_WEIGHTINKGS] DEFAULT ((0)) FOR [WEIGHTINKGS]
    PRINT 'Default constraint for WEIGHTINKGS added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PERKGRATE')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PERKGRATE] DEFAULT ((0)) FOR [PERKGRATE]
    PRINT 'Default constraint for PERKGRATE added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_CUSRID')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_CUSRID] DEFAULT ((0)) FOR [CUSRID]
    PRINT 'Default constraint for CUSRID added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_LMUSRID')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_LMUSRID] DEFAULT ((0)) FOR [LMUSRID]
    PRINT 'Default constraint for LMUSRID added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_DISPSTATUS')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_DISPSTATUS] DEFAULT ((0)) FOR [DISPSTATUS]
    PRINT 'Default constraint for DISPSTATUS added'
END

IF NOT EXISTS (SELECT * FROM sys.default_constraints WHERE name = 'DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PRCSDATE')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] ADD CONSTRAINT [DF_TRANSACTION_INVOICE_WEIGHT_DETAILS_PRCSDATE] DEFAULT (NULL) FOR [PRCSDATE]
    PRINT 'Default constraint for PRCSDATE added'
END

-- Add foreign key constraint for TRANDID to TRANSACTIONDETAIL (with CASCADE)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANSACTIONDETAIL')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]  
    WITH CHECK ADD CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANSACTIONDETAIL] 
    FOREIGN KEY([TRANDID])
    REFERENCES [dbo].[TRANSACTIONDETAIL] ([TRANDID])
    ON UPDATE CASCADE
    ON DELETE CASCADE
    
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] 
    CHECK CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANSACTIONDETAIL]
    
    PRINT 'Foreign key to TRANSACTIONDETAIL added (with CASCADE)'
END
ELSE
BEGIN
    PRINT 'Foreign key to TRANSACTIONDETAIL already exists'
END

-- Add foreign key constraints for PACKINGMASTER and PACKINGTYPEMASTER if they don't exist
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGMASTER] FOREIGN KEY([PACKMID])
    REFERENCES [dbo].[PACKINGMASTER] ([PACKMID])
    
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] CHECK CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGMASTER]
    PRINT 'Foreign key to PACKINGMASTER added'
END
ELSE
BEGIN
    PRINT 'Foreign key to PACKINGMASTER already exists'
END

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGTYPEMASTER')
BEGIN
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGTYPEMASTER] FOREIGN KEY([PACKTMID])
    REFERENCES [dbo].[PACKINGTYPEMASTER] ([PACKTMID])
    
    ALTER TABLE [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS] CHECK CONSTRAINT [FK_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKINGTYPEMASTER]
    PRINT 'Foreign key to PACKINGTYPEMASTER added'
END
ELSE
BEGIN
    PRINT 'Foreign key to PACKINGTYPEMASTER already exists'
END

-- Create indexes for better performance
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANDID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_TRANDID] ON [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]
    (
        [TRANDID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    PRINT 'Index on TRANDID created'
END
ELSE
BEGIN
    PRINT 'Index on TRANDID already exists'
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKMID')
BEGIN
    CREATE NONCLUSTERED INDEX [IX_TRANSACTION_INVOICE_WEIGHT_DETAILS_PACKMID] ON [dbo].[TRANSACTION_INVOICE_WEIGHT_DETAILS]
    (
        [PACKMID] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    PRINT 'Index on PACKMID created'
END
ELSE
BEGIN
    PRINT 'Index on PACKMID already exists'
END

PRINT 'TRANSACTION_INVOICE_WEIGHT_DETAILS table setup completed successfully!'
